name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: subcell_pipeline
        environment-file: ./environment.yml

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.10"
        version: 2.12.2
        cache: true

    - name: Cache environment
      id: cached-dependencies
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 0 # Increment this number if you wish to hard-refresh the cache.
      with:
        path: /usr/share/miniconda/envs/subcell_pipeline
        key: ${{ runner.os }}-${{ hashFiles('**/pdm.lock', '**/environment.yml') }}-${{ env.CACHE_NUMBER }}

    - name: Install dependencies
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      shell: bash -l {0}
      run: |
        conda create -n subcell_pipeline python=3.10
        conda activate subcell_pipeline
        conda env update --file environment.yml --prune
        pdm sync

    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        pdm run ruff check subcell_pipeline

    - name: Check with black
      shell: bash -l {0}
      run: |
        pdm run black --check subcell_pipeline

    - name: Check with isort
      shell: bash -l {0}
      run: |
        pdm run isort --check subcell_pipeline

    - name: Check with mypy
      shell: bash -l {0}
      run: |
        pdm run mypy subcell_pipeline

  result:
    if: ${{ always() && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    needs: [lint]

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Get lint result
      run: |
        if [[ ${{ needs.lint.result }} == "success" || ${{ needs.lint.result }} == "skipped" ]]; then
          exit 0
        else
          exit 1
        fi

    - name: Generate passing badge
      if: success()
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/lint.svg
        label: lint
        value: passing
        color: green
        template: docs/_badges/template.svg
        overwrite: true

    - name: Generate failing badge
      if: failure()
      uses: knightdave/anybadge-action@v1.1.0
      with:
        file: docs/_badges/lint.svg
        label: lint
        value: failing
        color: red
        template: docs/_badges/template.svg
        overwrite: true

    - name: Publish badge
      if: success() || failure()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/_badges
        target-folder: _badges
        clean: false
